name: Django

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a build step!"

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a test step!"
  oast:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v2

      - run: docker run --rm -v $(pwd):/src hysnsec/safety check -r requirements.txt --json > oast-results.json

      - uses: actions/upload-artifact@v2
        with:
          name: Safety
          path: oast-results.json
        if: always()                        # what is this for?

  integration:
    runs-on: ubuntu-20.04
    continue-on-error: true  # Allows the whole job to pass even if it fails
    steps:
      - name: Integration Step
        run: echo "This is the integration step!"
      - name: Simulate Failure
        run: exit 2

  artifact:
    runs-on: ubuntu-20.04
    steps:
      - name: Create a file
        run: echo "Hello" > hello.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.txt

  prod:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a prod step!"
  
    
