name: Django

on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a build step!"

  test:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a test step!"

  integration:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is the integration step!"
      - run: exit 2

  prod:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "This is a prod step!"
  
    
