
name: Django

on:
  push:
    branches: 
      - main
jobs:
  oast-snyk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install Node modules
        run: npm install

      - name: Run sonarQube
        run: |
          docker run --rm \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=amahmoodi181188_django-nv \
            -Dsonar.sources=/usr/src \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.organization=amahmoodi181188

      - uses: actions/upload-artifact@v4
        with:
          name: SQ
          path: Sonarqube-results.json
        if: always()        # what is this for?




  
  
